---
- name: Set Password
  hosts: localhost
  become: yes

  tasks:
  - name: Set passwd
    user:
      name: krishna
      update_password: always
      password: "{{'srikri5hnaydv' | password_hash('sha512', 'mysecretcode')}}"
